-- Create the users table and sequence
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(10) DEFAULT 'member' NOT NULL,
    reset_token VARCHAR2(100),
    reset_token_expiry TIMESTAMP
);

-- Create the email_verifications table and sequence
create table email_verifications (
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id           number not null,
   verification_code varchar2(32) not null,
   creation_date     timestamp with time zone default systimestamp,
   expiration_date   timestamp with time zone default systimestamp + interval '5' MINUTE,
   constraint fk_email_verifications_user foreign key (user_id)
      references users (user_id)
         on delete cascade
);

INSERT INTO USERS (name,email, password, role)
VALUES ('Rahul','rroy23133@gmail.com', '$2b$10$YiXyEC6ShYt03d4/tqb.jejiYEjYKtLIW/cozjmXMYUOzVd6.FDRa', 'admin');

-- Cleanup commands
truncate table email_verifications;
truncate table users;

drop table email_verifications;
drop table users;

commit;



-- Add a new attribute 'name' to the users table
ALTER TABLE USERS ADD name VARCHAR2(100);



