-- Create the users table and sequence
create table users (
   user_id            number
      generated by default as identity
   primary key,
   email              varchar2(100) not null unique,
   password           varchar2(255) not null,
   role               varchar2(10) default 'member' not null,
   reset_token        varchar2(100),
   reset_token_expiry timestamp
);

-- Create the email_verifications table and sequence
create table email_verifications (
   id                number
      generated by default as identity
   primary key,
   user_id           number not null,
   verification_code varchar2(32) not null,
   creation_date     timestamp with time zone default systimestamp,
   expiration_date   timestamp with time zone default systimestamp + interval '5' minute,
   constraint fk_email_verifications_user foreign key ( user_id )
      references users ( user_id )
         on delete cascade
);

insert into users (
   name,
   email,
   password,
   role
) values ( 'Rahul',
           'rroy23133@gmail.com',
           '$2b$10$YiXyEC6ShYt03d4/tqb.jejiYEjYKtLIW/cozjmXMYUOzVd6.FDRa',
           'admin' );

--------------------------------------------------------------------------------
-- 1) Publishers
--------------------------------------------------------------------------------
create table publishers (
   publisher_id number
      generated by default as identity
   primary key,
   name         varchar2(100) not null,
   address      varchar2(255),
   contact      varchar2(100)
);

--------------------------------------------------------------------------------
-- 2) Authors
--------------------------------------------------------------------------------
create table authors (
   author_id number
      generated by default as identity
   primary key,
   name      varchar2(100) not null,
   biography varchar2(4000)
);

--------------------------------------------------------------------------------
-- 3) Books
--------------------------------------------------------------------------------
create table books (
   book_id        number
      generated by default as identity
   primary key,
   title          varchar2(255) not null,
   isbn           varchar2(20),
   year_published integer,
   publisher_id   number not null,
   constraint fk_books_publisher foreign key ( publisher_id )
      references publishers ( publisher_id )
);

--------------------------------------------------------------------------------
-- 4) Book–Author link (weak entity BOOKAUTHOR)
--------------------------------------------------------------------------------
create table book_authors (
   book_id   number not null,
   author_id number not null,
   primary key ( book_id,
                 author_id ),
   constraint fk_book_authors_book foreign key ( book_id )
      references books ( book_id )
         on delete cascade,
   constraint fk_book_authors_author foreign key ( author_id )
      references authors ( author_id )
         on delete cascade
);

--------------------------------------------------------------------------------
-- 5) BookCount (weak entity identifying Book & Author)
--------------------------------------------------------------------------------
create table book_counts (
   book_id         number not null,
   author_id       number not null,
   total_books     number default 0 not null,
   available_books number default 0 not null,
   primary key ( book_id,
                 author_id ),
   constraint fk_book_counts_book foreign key ( book_id )
      references books ( book_id )
         on delete cascade,
   constraint fk_book_counts_author foreign key ( author_id )
      references authors ( author_id )
         on delete cascade
);

--------------------------------------------------------------------------------
-- 6) Members
--------------------------------------------------------------------------------
create table members (
   member_id             number
      generated by default as identity
   primary key,
   user_id               number not null unique,
   membership_start_date date not null,
   membership_end_date   date not null,
   current_loan_count    number default 0 not null,
   can_borrow            number(1) default 1 not null,
   member_type           varchar2(20),
   constraint fk_members_user foreign key ( user_id )
      references users ( user_id )
         on delete cascade
);

--------------------------------------------------------------------------------
-- 7) Loans
--------------------------------------------------------------------------------
create table loans (
   loan_id     number
      generated by default as identity
   primary key,
   member_id   number not null,
   book_id     number not null,
   loan_date   date not null,
   due_date    date not null,
   return_date date,
   fine        number default 0,
   constraint fk_loans_member foreign key ( member_id )
      references members ( member_id )
         on delete cascade,
   constraint fk_loans_book foreign key ( book_id )
      references books ( book_id )
);

--------------------------------------------------------------------------------
-- 8) Reminders (weak entity on Loan)
--------------------------------------------------------------------------------
create table reminders (
   loan_id            number not null,
   reminder_date      date not null,
   is_sent            number(1) default 0 not null,
   next_reminder_date date,
   primary key ( loan_id,
                 reminder_date ),
   constraint fk_reminders_loan foreign key ( loan_id )
      references loans ( loan_id )
         on delete cascade
);


-- Cleanup commands
truncate table email_verifications;
truncate table users;

drop table email_verifications;
drop table users;

INSERT INTO publishers (name, address, contact)
VALUES (
  'Mock Publisher Co.',
  '123 Library Lane, Booktown',
  'contact@mockpublisher.com'
);

COMMIT;


commit;



-- Add a new attribute 'name' to the users table
alter table users add name varchar2(100);